POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "type":"HealthCheck",
    "date": "2022-12-01",
    "description":"asdas",
    "specialist": "asdas",
    "diagnosisCodes": ["asdasd"], 
    "healthCheckRating":1
}

### hospital
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "type":"Hospital",
    "date": "2022-12-01",
    "description":"asdas",
    "specialist": "asdas",
    "diagnosisCodes": ["asdasd"], 
    "discharge":{
        "date": "2022-12-01", 
        "criteria":"asdasda"
    }

}

### OccupationalHealthcare
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "type":"OccupationalHealthcare",
    "date": "2022-12-01",
    "description":"asdas",
    "specialist": "asdas",
    "diagnosisCodes": ["asdasd"], 
    "employerName": "asdas",
    "sickLeave":{
        "startDate":"2022-12-01",
        "endDate":"2022-12-01"
    }

}