POST http://localhost:3001/api/patients/
Content-Type: application/json

{
    "name":"Jhon",
    "gender":"female",
    "occupation":"Cop",
    "dateOfBirth":"2021-01-01",
    "ssn":"123123"
}

### 
GET  http://localhost:3001/api/patients/
Content-Type: application/json

### 
GET  http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667
Content-Type: application/json