POST http://localhost:3001/api/patients/
Content-Type: application/json

{
    "name":"Jhon",
    "gender":"female",
    "occupation":"Cop",
    "dateOfBirth":"2021-01-01",
    "ssn":"123123"
}

### 
GET  http://localhost:3001/api/patients/
Content-Type: application/json